apiVersion: apps/v1
kind: Deployment
metadata:
  name: telemetry-ingester
  namespace: platform
spec:
  replicas: 1
  selector:
    matchLabels:
      app: telemetry-ingester
  template:
    metadata:
      labels:
        app: telemetry-ingester
    spec:
      containers:
        - name: telemetry-ingester
          image: telemetry-ingester:dev
          imagePullPolicy: Never
          env:
            - name: REDPANDA_BROKERS
              value: "redpanda.platform.svc.cluster.local:9092"
            - name: TIMESCALEDB_DSN
              value: "postgres://postgres:iicpc@timescaledb.platform.svc.cluster.local:5432/iicpc"
            - name: REDIS_ADDR
              value: "redis.platform.svc.cluster.local:6379"
            - name: MAX_ACCEPTABLE_P99_US
              value: "100000"
            - name: MAX_ACCEPTABLE_TPS
              value: "10000"
          resources:
            requests:
              memory: 64Mi
              cpu: "100m"
            limits:
              memory: 128Mi
              cpu: "250m"
          readinessProbe:
            exec:
              command: ["pgrep", "telemetry-ing"]
            initialDelaySeconds: 5
            periodSeconds: 5
