{{- if .Values.hpa.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: telemetry-ingester
  namespace: platform
  labels:
    {{- include "obarena.labels" . | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: telemetry-ingester
  minReplicas: {{ .Values.hpa.telemetryIngester.minReplicas }}
  maxReplicas: {{ .Values.hpa.telemetryIngester.maxReplicas }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.hpa.telemetryIngester.cpuTarget }}
{{- end }}
