apiVersion: v1
kind: Namespace
metadata:
  name: platform
  labels:
    {{- include "obarena.labels" . | nindent 4 }}
---
apiVersion: v1
kind: Namespace
metadata:
  name: builds
  labels:
    {{- include "obarena.labels" . | nindent 4 }}
---
apiVersion: v1
kind: Namespace
metadata:
  name: sandboxes
  labels:
    {{- include "obarena.labels" . | nindent 4 }}
---
apiVersion: v1
kind: Namespace
metadata:
  name: bots
  labels:
    {{- include "obarena.labels" . | nindent 4 }}
