apiVersion: v1
kind: Secret
metadata:
  name: obarena-timescaledb
  namespace: platform
  labels:
    {{- include "obarena.labels" . | nindent 4 }}
type: Opaque
data:
  password: {{ .Values.timescaledb.password | b64enc | quote }}
  dsn: {{ printf "postgres://postgres:%s@timescaledb.platform.svc.cluster.local:5432/obarena?sslmode=disable" .Values.timescaledb.password | b64enc | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: obarena-redis
  namespace: platform
  labels:
    {{- include "obarena.labels" . | nindent 4 }}
type: Opaque
data:
  password: {{ .Values.redis.password | b64enc | quote }}
