apiVersion: v1
kind: Service
metadata:
  name: seaweedfs
  namespace: platform
  labels:
    {{- include "obarena.labels" . | nindent 4 }}
spec:
  selector:
    app.kubernetes.io/name: seaweedfs
  ports:
    - name: s3
      port: 8333
    - name: master
      port: 9333
    - name: volume
      port: 8080
