apiVersion: v1
kind: Service
metadata:
  name: bot-orchestrator
  namespace: platform
  labels:
    {{- include "iicpc.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: bot-orchestrator
  ports:
    - name: http
      port: 8080
      targetPort: http
