apiVersion: apps/v1
kind: Deployment
metadata:
  name: build-service
  namespace: platform
  labels:
    {{- include "iicpc.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: build-service
  template:
    metadata:
      labels:
        {{- include "iicpc.labels" . | nindent 8 }}
        app.kubernetes.io/name: build-service
    spec:
      serviceAccountName: build-service
      nodeSelector:
        {{- toYaml .Values.nodeSelector.platform | nindent 8 }}
      tolerations:
        {{- toYaml .Values.tolerations.platform | nindent 8 }}
      containers:
        - name: build-service
          image: {{ include "iicpc.image" (list . "build-service") }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: REDPANDA_BROKERS
              value: "redpanda.platform.svc.cluster.local:9092"
            - name: SEAWEEDFS_ENDPOINT
              value: "http://seaweedfs.platform.svc.cluster.local:8333"
          resources:
            {{- toYaml .Values.resources.buildService | nindent 12 }}
          livenessProbe:
            exec:
              command: ["pidof", "build-service"]
            initialDelaySeconds: 15
            periodSeconds: 10
            failureThreshold: 3
