{{- if .Values.hpa.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: build-service
  namespace: platform
  labels:
    {{- include "iicpc.labels" . | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: build-service
  minReplicas: {{ .Values.hpa.buildService.minReplicas }}
  maxReplicas: {{ .Values.hpa.buildService.maxReplicas }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.hpa.buildService.cpuTarget }}
{{- end }}
