apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: build-artifacts
  namespace: platform
  labels:
    {{- include "iicpc.labels" . | nindent 4 }}
spec:
  accessModes: [ReadWriteOnce]
  {{- if .Values.storage.className }}
  storageClassName: {{ .Values.storage.className }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.storage.buildArtifacts.size }}
