apiVersion: v1
kind: Service
metadata:
  name: redpanda
  namespace: platform
  labels:
    {{- include "obarena.labels" . | nindent 4 }}
spec:
  selector:
    app.kubernetes.io/name: redpanda
  ports:
    - name: kafka
      port: 9092
    - name: admin
      port: 9644
    - name: http-proxy
      port: 8082
    - name: schema-registry
      port: 8081
